import { writeFileSync } from "node:fs";
import { SPRINGS, solveSpring } from "../src/motion/springs";

/** The generated stylesheet text. Also read by the test that keeps `springs.css` in sync. */
export function springsCss(): string {
	const lines = Object.entries(SPRINGS).flatMap(([name, spring]) => {
		const { easing, settleMs } = solveSpring(spring);
		return [`\t--rx-spring-${name}: ${easing};`, `\t--rx-spring-${name}-d: ${settleMs}ms;`];
	});
	return [
		"/* Generated by scripts/generate-springs.ts from src/motion/springs.ts. Do not edit by hand. */",
		":root {",
		...lines,
		"}",
		"",
	].join("\n");
}

if (import.meta.main) {
	const target = new URL("../src/styles/springs.css", import.meta.url);
	writeFileSync(target, springsCss());
	console.log(`wrote ${target.pathname}`);
}
